---
title: "Prediction models"
---

I considered two different binary outcomes. The first is being crowned "Miss Congeniality", and the second is winning the competition. 

**Model 1: Logistic Regression for the probability of winning the Miss Congeniality title**

Four models were developed to examine the probability of winning the Miss Congenialty title. Model 1 contained only demographic variables _age_ and _homestate_. Model 2 additionally contained _snatchgame_ (binary variable representing winning the Snatch Game episode) and _minichalw_ (continuous variable counting number of mini-challenge wins). In addition to the variables in Model 2, Model 3 additionally included the _rank_ variable (final rank in the competition). In addition to the variables in Model 2, Model 4 additionally contained the variables representing number of times ranking in each of the maxi challenges outcomes ( _nwin_, _nhighwin_, _nbot_, _nlowbot_, _nsafe_). In addition to the variables in Model 2, Model 5 additionally contains _nwin_ and _nhighwin_. I compared Accuracy and AIC to determine the final model. Model 4 had the lowest AIC and comparable Accuracy to the other models (AIC: 143.88 and Accuracy : 0.9344) so I selected it as the final model. 
The only covariate that was found to be significantly associated withe the outcome in this model was nhighwin (p-value: 0.028). 
I also ran a prediciton model that was able to predict only 2 of the 14 winners of miss congeniality (Nina Flowers and Yara Sofia) (specificity 0.14) but did not predict any non-winners to obtain the title (sensitivity 1.00).


**Model 2: Logistic Regression for the probability of winning the competition**

Three models were developed to examine the probability of winning the competition. Model 1 contained only demographic variables _age_ and _homestate_. Model 2 additionally contained _snatchgame_ (binary variable representing winning the Snatch Game episode) and _minichalw_ (continuous variable counting number of mini-challenge wins). In addition to the variables in Model 2, Model 3 additionally contained the variables representing number of times ranking in each of the maxi challenges outcomes ( _nwin_, _nhighwin_, _nbot_, _nlowbot_, _nsafe_). I compared Accuracy and AIC to determine the final model. Model 3 had the lowest AIC (AIC: 126.69) and an Accuracy of 0.95 and was selected it as the final model. 
The only covariate that was found to be significantly associated withe the outcome in this model was snatchgame (p-value: 0.0436). 
I also ran a prediciton model that was able to predict 10 of the 14 winners (specificity 0.71) and did predict 3 winners to obtain the title (Manila Luzon, Alaska, and Rosé) (sensitivity 0.9822).

